name: packer_build


on:
  pull_request:
    branches:
      - main
      
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Packer build
        uses: riznob/packer-build-action@v1.1
        with:
          templateFile: 'ami.json'
          workingDir: '.'
        env:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: us-east-1